### ISSUE TITLE
Trouble running grunt file

### ISSUE THREAD

**Issue by icecreammatt** [YuzuJS/WinningJS-todo#33]
I am currently using Cygwin on Windows 8. I was curious what you are using to run your grunt file. I noticed grunt has changed from grunt.js to Gruntfile.js 

I am new to using grunt so maybe I am missing something.
Is there some step I am missing?

``` sh
$ npm install
...

mattc@MATTC-MACMINI /c/users/mattc/projects/WinningToDo (master)
$ grunt
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.

mattc@MATTC-MACMINI /c/users/mattc/projects/WinningToDo (master)
$ mv grunt.js Gruntfile.js

mattc@MATTC-MACMINI /c/users/mattc/projects/WinningToDo (master)
$ grunt
Running "WinningJS-build" task
path.js(116,15): error TypeError: Arguments to path.resolve must be strings
Warning: Arguments to path.resolve must be strings Use --force to continue.

Aborted due to warnings.

mattc@MATTC-MACMINI /c/users/mattc/projects/WinningToDo (master)
$ grunt --version
grunt-cli v0.1.9
grunt v0.4.1
```

**Comment by domenic** [comment]
Unfortunately, this project uses Grunt 0.3.x. Even more unfortunately, in our package.json we specified `">= 0.3.17"`, so if you try to install it now, Grunt 0.4.x will be installed and everything will break!

You can probably fix this by editing `package.json`. I will see if I can spend some time upgrading the project to 0.4.x.

**Comment by icecreammatt** [comment]
@domenic Thanks for the fast feedback. I did try experimenting with changing the version to`== 0.3.17`, but I got similar output:

``` sh

mattc@MATTC-MACMINI /c/users/mattc/projects/WinningToDo (master)
$ grunt --version
grunt-cli v0.1.9
grunt v0.3.17

mattc@MATTC-MACMINI /c/users/mattc/projects/WinningToDo (master)
$ grunt
Running "WinningJS-build" task
path.js(116,15): error TypeError: Arguments to path.resolve must be strings

TypeError: Arguments to path.resolve must be strings


```

**Comment by domenic** [comment]
Ugh, I bet Grunt 0.3.x doesn't work with Node 0.10.x :(.

**Comment by domenic** [comment]
Hold on, upgrading everything to Grunt 0.4; I think it will work.

**Comment by domenic** [comment]
OK, everything's all upgraded now (and the dependency versions are mostly pinned, thank goodness).

The underlying problem was actually in [browserify-deoptimizer](https://github.com/domenic/browserify-deoptimizer), and I fixed it 3 months ago but forgot to do `npm publish`. Womp womp...

**Comment by icecreammatt** [comment]
Thanks for the fast response. Ill test it first thing tomorrow.

**Comment by icecreammatt** [comment]
@domenic Thanks for the fast fix. It is working now :+1:
